### ISSUE TITLE
module not found vue-hot-reload-api

### ISSUE THREAD

**Issue by Lee182** [vuejs-templates/pwa#127]
might want to add it to devDependicies.

```bash
pnpm install -D vue-cli
pnpx -c "vue init pwa"
pnpm install
pnpm run dev
```

**Comment by jeffposnick** [comment]
The `pwa` template includes `package.json` which has [`vue-loader`](https://github.com/vuejs-templates/pwa/blob/development/template/package.json#L95) as a dependency, and `vue-loader` has [`vue-hot-reload-api`](https://github.com/vuejs/vue-loader/blob/master/package.json#L54) as a dependency.

When I go through a `vue init pwa` followed by `npm install`, `vue-hot-reload-api` shows up in my `node_modules` by virtue of that transitive dependency.

Perhaps what you're seeing is a side-effect of using `pnpm` instead of `npm` (or `yarn`)?
