### ISSUE TITLE
Nginx config failing

### ISSUE THREAD

**Issue by tvld** [vuejs-templates/pwa#133]
Using Nginx and a proxy, the documented and ``README`` comments in #115 fail:
```
    location / {
      gzip_static on;
      proxy_pass      http://localhost:8082;
      include         /etc/nginx/proxy.conf;
    }

    # see https://github.com/vuejs-templates/pwa/blob/development/docs/prevent_caching.md
    location ~ (index.html|service-worker.js)$ {
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, oxy-revalidate, max-age=0';
      if_modified_since off;
         expires off;
         etag off;
    }
```
FF57 browser Error:
```
Error during service worker registration: 
TypeError: ServiceWorker script at https://www.lorinthe.com/service-worker.js for scope https://www.lorinthe.com/ encountered an error during installation.
aboutus:1:647
Failed to register/update a ServiceWorker for scope ‘https://www.lorinthe.com/’: Load failed with status 404 for script ‘https://www.lorinthe.com/service-worker.js’.
```
If using just ``location /index.html {...}`` no errors, but then updating the site becomes a pain: Subpages ``mysite.com/aboutus`` are updated reload on mobile browsers but the home page ``mysite.com`` stays on old version. (On desktop ``Ctrl F5`` works though.)

**Comment by tvld** [comment]
Strangely,  the config below does not generate errors. 

That said, the whole idea for not caching the index and sw.js _is not good_ imho.

This approach leads to version conflicts:  our pwa ends up in mutliple versions at same time: the home page has old version that  from the sw cache while all the subpages do update to the latest version.

```
    # see https://github.com/vuejs-templates/pwa/blob/development/docs/prevent_caching.md
    location index.html {
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
         expires off;
         etag off;
    }
    location service-worker.js {
      add_header Last-Modified $date_gmt;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      if_modified_since off;
         expires off;
         etag off;
    }

    # Pass request to the Docker Container hosting the site
    location / {
      gzip_static on;
      proxy_pass      http://localhost:8082;
      include         /etc/nginx/proxy.conf;
    }
```

**Comment by jeffposnick** [comment]
If you'd like to prevent new versions of the service worker from taking over immediately, then the best course of action would be to set [`skipWaiting: false`](https://github.com/GoogleChromeLabs/sw-precache#skipwaiting-boolean) alongside the other options in the service worker configuration:

https://github.com/vuejs-templates/pwa/blob/32b20a50b2315cb8cdb3c170ef474583b4600d38/template/build/webpack.prod.conf.js#L110-L116

Relying on cache control headers to prevent a new service worker from activating is not going to give you the behavior you expect consistently. Leaving out `skipWaiting`, on the other hand, [will ensure](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates) that the updated service worker doesn't take over until all existing tabs are closed. (Many developers want their new resources available immediately, which is why we default to `true`, but that's up to you.)

I'm CC: @ahus1 regarding the nginx configuration, as I don't personally have experience setting that up.

**Comment by tvld** [comment]
Thank you. I would like to have new resources avail immediately... but right now it does not. That was the point. That said, I do think it might have to do with some browsers not fully behaving on mobile... We are diving into it and report back on this if there is.

**Comment by jeffposnick** [comment]
If you'd like to have new resources available immediately, then you definitely want to continue disabling HTTP caching when serving `/service-worker.js`.

Once you've done that, you do have some extra control over the experience, depending on whether you enable `skipWaiting` or not. There's some very thorough background material at

- https://redfin.engineering/service-workers-break-the-browsers-refresh-button-by-default-here-s-why-56f9417694
- https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68

which cover some of the considerations and offers different approaches.

We try to default to something reasonable in this template, but you do have the control to go in and change things up as you see fit.

**Comment by tvld** [comment]
Excellent reading material; thank you :+1:
