### ISSUE TITLE
Service worker not restoring partial missing artifacts in cache

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuejs-templates/pwa#145]
Hi,

When experimenting with the service worker, I noticed that if I delete one of the resources from the cache and then reload the page, that the service worker isn't smart enough to pull the missing resource into the cache once the application goes on-line. However, unregister the service worker and then refreshing the page forces an update to the cache, restoring all static artifacts. Is this the expected behavior of the service worker?

Thanks

**Comment by LinusBorg** [comment]
the Service Worker cache itself is not "intelligent", so this is expected. 

It's probably possible to write something that does this, but that would have to be addressed in the repos of [sw-precache](https://github.com/GoogleChromeLabs/sw-precache) and/or [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin), which this template is using to do the caching.

**Comment by jeffposnick** [comment]
Thats the expected behavior, and it's not likely to change.

As a developer, you're obviously free to experiment with manually updating the precached entries, the expectation is that end users will have their caches managed by the auto-generated service worker code (and the embedded precache manifest). If a user/developer does somehow end up in a state where a precached resource has been removed from the cache, the service worker will automatically fall back on the network until the next time the service worker is redeployed.

Caches that need more flexibility, such as imposing automatic expiration policies, are best handled via a [runtime caching policy](https://github.com/GoogleChromeLabs/sw-precache#runtimecaching-arrayobject), not precaching.
