### ISSUE TITLE
Missing vendor.js files

### ISSUE THREAD

**Issue by nwaughachukwuma** [vuejs-templates/pwa#156]
@jeffposnick , @addyosmani, @MaxMilton and everyone, my app is doing great offline thanks to this awesome template. I am really delighted about the template. But there's a little challenge. Whenever I try to visit the app after a period of inactivity, I get a blank screen (image below), and on chrome debugger, I see that it could not fetch the hashed vendor.js file. Also the vendor.js file is missing in the list of js files in the frames. And it shows an error reading the manifest.js file. This is like what is left for me to have a complete offline application. I am hoping there's a fix for this. Thanks

![blank_screen](https://user-images.githubusercontent.com/20521315/35266674-3ee11170-0024-11e8-8c2c-33931651b452.png)
![loses_files](https://user-images.githubusercontent.com/20521315/35266679-423dfef0-0024-11e8-9046-348cbed985c5.png)
![image](https://user-images.githubusercontent.com/20521315/35321875-8ab2f5fe-00e8-11e8-95bb-6b8bd820d28c.png)

**Comment by maxmilton** [comment]
Does this happen even with a freshly install project using this template?

**Comment by nwaughachukwuma** [comment]
@MaxMilton I have not inspected it. Will do that soon enough. But what do you think the problem might be

**Comment by jeffposnick** [comment]
- Is there a public URL that we could visit to reproduce this? If so, how long do you need to wait in between the initial load and the period of time when this error crops up?
- Have you potentially redeployed your web app to its production server in between your initial visit and returning later on, when you see this error?
- Can you share the contents of your generate service worker file, which includes the list of URLs that were meant to be precached? Do you see a URL corresponding to the JS file that fails to load?

**Comment by nwaughachukwuma** [comment]
Hi @jeffposnick, thanks for quick reply. I will give my answer in the order you have asked them:

1. You can access the platform here: https://dashboards.dprsconnect.org.ng/ All you need to do is revisit the platform after a period of inactivity, don't know how to quantify this really. But say you put off your internet, and hibernate your system or put in sleep mode for a while. When you put it back on, revisit the URL with the internet off. That might reproduce it.

2. No, this is not the situation. I had it deployed once and didn't redeploy in between visits.

3. I didn't see the corresponding js File. However it is generated in the **dist** folder.  Please check following link to see the full content of the generated service worker file: https://pastebin.com/Ck3AvhZn.

I hope my response is detailed enough. Thanks so much

**Comment by jeffposnick** [comment]
![image](https://user-images.githubusercontent.com/1749548/35340642-a59eb46c-00f1-11e8-9e73-a54d2d8a0861.png)

The problem is that your vendor bundle is 7.5 megabytes, and by default `sw-precache` won't cache anything larger than 2 megabytes. So your vendor bundle isn't available offline. And then when you immediately visit your web app right after waking up a system from sleep, you're effectively offline (if you reload quickly enough, before your WiFi connection has reestablished). I could simulate the same error just by forcing offline mode in Chrome's DevTools and then reloading the page.

You've got a few options:
1. Don't do anything, and accept the fact that your vendor bundle won't be available offline and there might be versioning mismatches when you redeploy your site.
2. Increase the value of the [`maximumFileSizeToCacheInBytes` config option](https://github.com/GoogleChromeLabs/sw-precache#maximumfilesizetocacheinbytes-number) that's passed to the `SWPrecacheWebpackPlugin` config.
3. Reduce the size of your vendor bundle, by breaking it down into multiple, smaller bundles or (preferably!) removing unused third part code. A tool like https://www.npmjs.com/package/webpack-bundle-analyzer can help there.

I'd strongly suggestion that you go with the third option, since your users will really benefit from having to download and parse less JavaScript.

**Comment by nwaughachukwuma** [comment]
Thanks so much @jeffposnick your response is really helpful. What I have done is remove certain unnecessary dependencies, thus reducing the vendor.js file size to about 2 mb. And it's working perfectly now. Really grateful for this help. Thanks also @MaxMilton

**Comment by nwaughachukwuma** [comment]
Thanks so much @jeffposnick your response is really helpful. What I have done is remove certain unnecessary dependencies, thus reducing the vendor.js file size to about 2 mb. And it's working perfectly now. Really grateful for this help. Thanks also @MaxMilton

**Comment by nwaughachukwuma** [comment]
Hi @jeffposnick I have noticed that running my application over https://dashboards.dprsconnect.org.ng/ still gives me over 7mb but same application over https://dhis2-daily-reporting.firebaseapp.com gives me <2mb. What could be responsible for this? As the consequence is that the former takes long to load than the later, and the behavior is also funny. 

Mind you I havehad to adopt the option of increasing maximumFileSizeToCacheInBytes to about 10mb just to accommodate this behavior.
