### ISSUE TITLE
Lazy Loading loads all the components at the same time even when they are not required

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs-templates/pwa#95]
So I'm lazy loading view components in vue-router like this
``` js
const Hello = () => import('@/components/Hello')
const Hello2 = () => import('@/components/Hello2')
```

The expected behaviour is when I **http://localhost:8080/#/** it should only load 0.js, the javascript of the Hello component. But in the following screenshot you can see that is loading 0.js and 1.js (Hello2 code), and 1.js again.

![image](https://user-images.githubusercontent.com/3449006/31612764-ca02a8d0-b278-11e7-80ae-03e9cb58a535.png)

This error is not happening in the vue-webpack template.

Here is a repo with all the code reproducing the error
https://github.com/ellipticaldoor/vue-pwa-lazy-loading-error

**Comment by LinusBorg** [comment]
"It's not a bug, it's a feature"

The service worker is pre-loading all routes chunks (and all the others), so the whole app works offline.

**Comment by ellipticaldoor** [comment]
Haha, I see. But if I have a big app the first load can be slow.

Uhm, now I don't know if I prefer this behaviour or just loading and caching something only when is required.

**Comment by LinusBorg** [comment]
> Haha, I see. But if I have a big app the first load can be slow. 

As I said, the service worker loads these files in the background, while your app is already running. Your app will start as fast as it would without this behaviour.

> Uhm, now I don't know if I prefer this behaviour or just loading and caching something only when is required.

Then that's not really a PWA, which, amongst other things, should work offline as good as possible.

**Comment by ellipticaldoor** [comment]
Okay! Makes sense.

**Comment by folmert** [comment]
@LinusBorg Sorry, but I'm still not convinced.

This doesn't look like "service worker loads these files in the background".

In Chrome, open Network tab and change Online to Slow 3G to simulate slow internet connection. Reload with Ctrl+F5.

![lazy loading](https://i.imgur.com/Dhii1uT.jpg)

What I see is that it **waits for all files** to be loaded before the app is rendered. Take a look on the order of loaded assets and time it took. For me the app was visible only after the last one was loaded.

**Comment by LinusBorg** [comment]
1. If you think is is a real issue, please open a fresh one. comemnts in closed issue might go unnoticed by the people actually maintaining this template.
2. I can't follow our explanation in our screenshots as I can't read all the file names or understand how they are related in your app.
3. A runnable code example is much more helpful in debugging problems you might have.

**Comment by folmert** [comment]
Didn't want to duplicate this one, as I'm having exact same concerns as the issue author (@ellipticaldoor) and I don't think my own project's config is making a difference - it's more about the general idea of how this is supposed to work.

But just to make sure I cloned his repo (https://github.com/ellipticaldoor/vue-pwa-lazy-loading-error) and it's also behaving same way as mine:

![lazy load](https://i.imgur.com/kNoTYkT.jpg)

Shouldn't it load 0.js (Hello2.vue) in the period of inactivity after the app is loaded and running? I have a feeling that it's not working correctly.

**Comment by LinusBorg** [comment]
> Shouldn't it load 0.js (Hello2.vue) in the period of inactivity after the app is loaded and running?

No - the serviceworker will start loading all these files as soon as it has started. That doesn't mean that the app *waits* for all of them.

And depending on which route you are at, (`/` or `/hello2`), the app has to wait for that route's chunk to be lazy-loaded before the app can work.

**Comment by folmert** [comment]
> And depending on which route you are at, (/ or /hello2), the app has to wait for that route's chunk to be lazy-loaded before the app can work.

That is clear as day.

But the crucial question: is precaching lazy loaded chunks slowing down the initial load?

At first you write that app doesn't wait for them, but you agree that optimal way would be to fetch them after the boot, so I'm a bit confused.

Where should I look If I'd like to optimize it and make it work like in this [article](https://medium.com/@prowe214/lazy-loading-vs-preloading-modules-which-should-you-choose-85a1fb71a24)?

**Comment by LinusBorg** [comment]
It seems the serviceworker is injected into the main `index.html` template:

https://github.com/vuejs-templates/pwa/blob/development/template/build/webpack.prod.conf.js#L74-L75

And that file can be found here:

https://github.com/vuejs-templates/pwa/blob/development/template/build/service-worker-prod.js

So basically, you would have to run the code of that `service-worker-prod.js` file within you app after the first navigation has finished. So maybe as a once-time all in a `router.afterEach()`

**Comment by jeffposnick** [comment]
Based on the screenshots posted, I believe that the traffic might be explained by the use of [`<link rel="preload|prefetch">`](https://github.com/vuejs-templates/pwa/blob/development/template/index.html#L24-L27) within `index.html`, not by service worker's precaching.

Requests that originate from within the service worker are displayed in the Network DevTools panel with a [little gear icon](https://stackoverflow.com/questions/33590378/status-code200-ok-from-serviceworker-in-chrome-network-devtools/33655173#33655173) next to them.

That doesn't change the fact that this traffic is intentional, and the browser has logic in place to fetch those resources with the appropriate priority without delaying the rendering on other items on the page.

**Comment by folmert** [comment]
Yea, I've noticed that HtmlWebpackPlugin is injecting those preload and prefetch scripts - but they are also added to precacheConfig in service-worker.js.

So I've removed the scripts from index.html to force service worker to load them. And it works, a lot of requests with gear icon are made at the startup now, so seems like they are being cached.

However, I'm unable to use what service worker cached.

When I actually request them (by going to view which dynamically imports them), they are not loaded from service worker - they are loaded again from the network. Service worker seems to be bypassed. 

Also when I simulate no connection in DevTools, and request a resource which was cached by SW, I get:

> net::ERR_INTERNET_DISCONNECTED (from Webpack code)
> Error: Loading chunk 4 failed. (from Vue Router code)

There is no error from service-error though.

**Edit: I figured it out after reading your answer in [this thread](**url**). After I moved everything to localhost and opened from there the requests have now information at Size: (from ServiceWorker) 🥇 
Turns out SW have very restrictive security policies.**
